version: '2'
services:
  graphite:
    build:
      context: ./graphite
    mem_limit: 1G
    ports: 
    - 80:80
    - 2003-2004:2003-2004
    - 2023-2024:2023-2024
    - 8125:8125/udp
    - 8126:8126
    volumes:
    #  - ./graphite/configs:/opt/graphite/conf
      - /home/graphite-database:/opt/graphite/storage/whisper
    #network_mode: "host"

  grafana:
    image: grafana/grafana:master
    ports:
      - 3000:3000
    #network_mode: "host"

  stats_collector:
    build:
      context: ./collector
    container_name: collect
    restart: on-failure
    environment:
        - COLLECTION_INTERVAL=30
        - PROXY_ADDRESS=scspw0536729001.ict.englab.netapp.com:8080
    #network_mode: "host"

volumes:
  grafana_vol:
