version: '2'
services:

  netapp_web_services:
    image: ${PROJ_NAME}/webservices:${TAG}
    container_name: webservices
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - ACCEPT_EULA=true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    volumes:
      - arraydata:/opt/netapp/santricity_web_services_proxy/working/arraydata.xml

  graphite:
    image: ${PROJ_NAME}/graphite:${TAG}
    build:
      context: ./graphite
    container_name: graphite
    restart: unless-stopped
    depends_on:
      - netapp_web_services
    mem_limit: 2G
    ports:
      - 80
      - 2003-2004
      - 2023-2024
      - 8125/udp
      - 8126
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    volumes:
    #  - ./graphite/configs:/opt/graphite/conf
      - ./graphite-database:/opt/graphite/storage/whisper

  grafana:
    image: ${PROJ_NAME}/grafana:${TAG}
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - graphite
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

  stats_collector:
    image: ${PROJ_NAME}/collector:${TAG}
    depends_on:
      - grafana
    container_name: collector
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
        - USERNAME=admin
        # you can modify the password for webservices here
        # otherwise it will default to admin
        #- PASSWORD=myPass
        - COLLECTION_INTERVAL=30
        # You can use this to modify the location of the Web Services instance if you have one running externally you wish to use
        #- PROXY_ADDRESS=webservices:8080

volumes:
  grafana_vol:
  arraydata:
