version: '2'
services:

  netapp_web_services:
    image: webservices:3.10
    build:
      context: ./webservices
    container_name: webservices
    restart: on-failure
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - ACCEPT_EULA=true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    volumes:
      - arraydata:/opt/netapp/santricity_web_services_proxy/working/arraydata.xml

  graphite:
    image: graphite:${TAG}
    build:
      context: ./graphite
    container_name: graphite
    depends_on:
      - netapp_web_services
    mem_limit: 2G
    ports: 
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    volumes:
    #  - ./graphite/configs:/opt/graphite/conf
      - ./graphite-database:/opt/graphite/storage/whisper

  grafana:
    image: grafana/grafana:5.3.4
    depends_on:
      - graphite
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

  stats_collector:
    image: collector:${TAG}
    build:
      context: ./collector
    depends_on:
      - grafana
    container_name: collector
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
        - USERNAME=admin
        # you can modify the password for webservices here
        # otherwise it will default to admin
        #- PASSWORD=myPass
        - COLLECTION_INTERVAL=30
        - PROXY_ADDRESS=netapp_web_services:8080

volumes:
  grafana_vol:
  arraydata:
